### PR TITLE
Feature/use poetry and add more linting actions

### PR DESCRIPTION
**Pull request by drewsilcock**
This moves from `requirements.txt` to Poetry and drops Python 2 support code. It also adds the following actions:

- Flake8 linter to check styling and PEP8 compliance.
- isort import sorter.
- pylint error checker
- mypy static type checker

Also in a separate job:

- Pylint HTML report generation (includes code metrics, etc.)

If this looks good to you, I can start getting these same actions ported across to other repos (e.g. juriscraper, courtlistener).

### CODE REVIEW

**Comment by mlissner** [comment]
Looks good to me. We'll find things, I imagine, but I can't think of how to find them in advance of rolling this out various places. 

One thing: Is the lock file...right? It's huge! I really want to believe that you accidentally put one in from some other project. Like, it has `cryptography` as a dependency. Wat?!

**Comment by drewsilcock** [comment]
Migrating an existing codebase to these linting rules if fairly significant (especially the imports if they've not been sorted previously).

Yeah the lockfile... that's modern dependencies for you, at least it doesn't rely on leftpad 😆 

This is indeed the correct lockfile - I've put the dependency tree below if you're interested. It seems most of this is due to Twine which I carried out from the previous `requirements_dev.txt` but in truth Twine isn't needed anymore because Poetry itself will handle the PyPI uploads, so we can drop that (which is why cryptography was needed 🙂 ).

```
black 20.8b1 The uncompromising code formatter.
|-- appdirs *
|-- click >=7.1.2
|-- mypy-extensions >=0.4.3
|-- pathspec >=0.6,<1
|-- regex >=2020.1.8
|-- toml >=0.10.1
|-- typed-ast >=1.4.0
`-- typing-extensions >=3.7.4
flake8 3.8.4 the modular source code checker: pep8 pyflakes and co
|-- mccabe >=0.6.0,<0.7.0
|-- pycodestyle >=2.6.0a1,<2.7.0
`-- pyflakes >=2.2.0,<2.3.0
isort 5.6.4 A Python utility / library to sort Python imports.
mypy 0.790 Optional static typing for Python
|-- mypy-extensions >=0.4.3,<0.5.0
|-- typed-ast >=1.4.0,<1.5.0
`-- typing-extensions >=3.7.4
pylint 2.6.0 python code static checker
|-- astroid >=2.4.0,<=2.5
|   |-- lazy-object-proxy >=1.4.0,<1.5.0 
|   |-- six >=1.12,<2.0 
|   `-- wrapt >=1.11,<2.0 
|-- colorama *
|-- isort >=4.2.5,<6
|-- mccabe >=0.6,<0.7
`-- toml >=0.7.1
twine 3.2.0 Collection of utilities for publishing packages on PyPI
|-- colorama >=0.4.3
|-- keyring >=15.1
|   |-- jeepney >=0.4.2 
|   |-- pywin32-ctypes <0.1.0 || >0.1.0,<0.1.1 || >0.1.1 
|   `-- secretstorage >=3.2 
|       |-- cryptography >=2.0 
|       |   |-- cffi >=1.8,<1.11.3 || >1.11.3 
|       |   |   `-- pycparser * 
|       |   `-- six >=1.4.1 
|       `-- jeepney >=0.4.2 (circular dependency aborted here)
|-- pkginfo >=1.4.2
|-- readme-renderer >=21.0
|   |-- bleach >=2.1.0 
|   |   |-- packaging * 
|   |   |   |-- pyparsing >=2.0.2 
|   |   |   `-- six * 
|   |   |-- six >=1.9.0 (circular dependency aborted here)
|   |   `-- webencodings * 
|   |-- docutils >=0.13.1 
|   |-- pygments >=2.5.1 
|   `-- six * (circular dependency aborted here)
|-- requests >=2.20
|   |-- certifi >=2017.4.17 
|   |-- chardet >=3.0.2,<4 
|   |-- idna >=2.5,<3 
|   `-- urllib3 >=1.21.1,<1.27 
|-- requests-toolbelt >=0.8.0,<0.9.0 || >0.9.0
|   `-- requests >=2.0.1,<3.0.0 
|       |-- certifi >=2017.4.17 
|       |-- chardet >=3.0.2,<4 
|       |-- idna >=2.5,<3 
|       `-- urllib3 >=1.21.1,<1.27 
|-- rfc3986 >=1.4.0
`-- tqdm >=4.14
```

**Comment by drewsilcock** [comment]
Pushed an update to remove Twine from dependencies.

**Comment by mlissner** [comment]
This is great, thank you for all your efforts!

**Comment by mlissner** [comment]
@drewsilcock when you get a sec, can you explain whether the pyflakes integration is working? I don't get the impression it's doing anything, and it's hard to actually tell since it uses a action somebody else developed. I'm just surprised we haven't heard *anything* from it in that other PR.

**Comment by drewsilcock** [comment]
The flake8 action is supposed to do fancy things like annotations on the PR but it does seem odd that it didn't raise any issues. I'll try an experimental PR at some point to see whether it's annotating correctly.

**Pull request merged**
